"""
Panel 8 - Heavy-tail stress test (plotting)
===========================================

Loads the NPZ generated by `heavy_tail_demo.py` and renders the figure described
in the protocol: three boxplots (K_eff, false-outlier rate, Frobenius error)
plus a diagnostic histogram for the bulk edge.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt
import matplotlib
import numpy as np


COLORS = {
    "sample": "#D55E00",
    "tyler": "#009E73",
    "grid": "#BFBFBF",
    "bulk_band": "#999999",
}

matplotlib.rcParams.update({
    "font.size": 10,
    "axes.labelsize": 11,
    "axes.titlesize": 12,
    "xtick.labelsize": 9,
    "ytick.labelsize": 9,
    "legend.fontsize": 9,
    "figure.titlesize": 14,
    "font.family": "sans-serif",
    "font.sans-serif": ["Arial", "DejaVu Sans"],
    "axes.linewidth": 1.0,
})


def load_results(path: Path) -> List[Dict]:
    data = np.load(path, allow_pickle=True)
    results = data["results"]
    return [dict(item) for item in results]


def nu_label(nu: float) -> str:
    return r"$\nu=\infty$" if np.isinf(nu) else rf"$\nu={int(nu)}$"


def group_metric(results: List[Dict], metric: str) -> Dict[float, Dict[str, np.ndarray]]:
    grouped: Dict[float, Dict[str, List[np.ndarray]]] = {}
    for cond in results:
        nu = float(cond["condition"]["nu"])
        grouped.setdefault(nu, {"sample": [], "tyler": []})
        for method in ("sample", "tyler"):
            values = np.asarray(cond["metrics"][method][metric]).ravel()
            if values.size:
                grouped[nu][method].append(values)
    aggregated: Dict[float, Dict[str, np.ndarray]] = {}
    for nu, sub in grouped.items():
        aggregated[nu] = {}
        for method in ("sample", "tyler"):
            if sub[method]:
                aggregated[nu][method] = np.concatenate(sub[method])
            else:
                aggregated[nu][method] = np.empty(0)
    return aggregated


def plot_grouped_boxplot(ax, grouped, ylabel, title):
    def _sort_key(val: float) -> Tuple[int, float]:
        if np.isinf(val):
            return (1, 0.0)
        return (0, float(val))

    nu_values = sorted(grouped.keys(), key=_sort_key)
    methods = ("sample", "tyler")
    positions = []
    data = []
    colors = []
    group_centers = []
    width = 0.55
    gap = len(methods) + 0.5

    for idx, nu in enumerate(nu_values):
        base = idx * gap
        group_centers.append(base + 0.5)
        for j, method in enumerate(methods):
            positions.append(base + j)
            data.append(grouped[nu][method])
            colors.append(COLORS[method])

    box = ax.boxplot(
        data,
        positions=positions,
        widths=width,
        patch_artist=True,
        showfliers=False,
    )
    for patch, color in zip(box["boxes"], colors):
        patch.set_facecolor(color)
        patch.set_alpha(0.5)
        patch.set_edgecolor(color)
    for median in box["medians"]:
        median.set_color("#333333")
        median.set_linewidth(1.2)

    ax.set_xticks(group_centers, [nu_label(nu) for nu in nu_values], rotation=0)
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.grid(True, axis="y", linestyle="--", alpha=0.4, color=COLORS["grid"])

    handles = [
        plt.Line2D([0], [0], color=COLORS["sample"], lw=4, label="SCM (sample)"),
        plt.Line2D([0], [0], color=COLORS["tyler"], lw=4, label="Tyler"),
    ]
    ax.legend(handles=handles, loc="upper right")


def plot_bulk_hist(ax, results: List[Dict]):
    sample_bulk = []
    tyler_bulk = []
    edges = []
    for cond in results:
        sample_bulk.append(cond["metrics"]["sample"]["bulk_edge"])
        tyler_bulk.append(cond["metrics"]["tyler"]["bulk_edge"])
        edges.append(cond["thresholds"]["mp_edge_cushioned"])

    sample_vals = np.concatenate(sample_bulk)
    tyler_vals = np.concatenate(tyler_bulk)
    edges = np.asarray(edges)

    bins = np.linspace(
        min(sample_vals.min(), tyler_vals.min()),
        max(sample_vals.max(), tyler_vals.max()),
        30,
    )

    ax.hist(sample_vals, bins=bins, alpha=0.45, color=COLORS["sample"], label="SCM bulk λ_max")
    ax.hist(tyler_vals, bins=bins, alpha=0.45, color=COLORS["tyler"], label="Tyler bulk λ_max")

    edge_min, edge_med, edge_max = edges.min(), np.median(edges), edges.max()
    ax.axvspan(edge_min, edge_max, color=COLORS["bulk_band"], alpha=0.2, label=r"$(1+\eta)\lambda_+^{MP}$ range")
    ax.axvline(edge_med, color="#333333", linestyle="--")

    ax.set_xlabel(r"$\lambda_{\max}$ (bulk)")
    ax.set_ylabel("count")
    ax.set_title(r"8D) Bulk edge diagnostics")
    ax.grid(True, axis="y", linestyle="--", alpha=0.4, color=COLORS["grid"])
    ax.legend()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot Panel 8 heavy-tail stress test.")
    parser.add_argument("--input", type=Path, default=Path("graphs/panel8/output/panel8_heavy_tail_data.npz"),
                        help="NPZ file generated by heavy_tail_demo.py")
    parser.add_argument("--output", type=Path, default=Path("graphs/panel8/output/panel8_heavy_tail.pdf"),
                        help="Where to save the PDF figure.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    data = load_results(args.input)

    grouped_keff = group_metric(data, "keff")
    grouped_false = group_metric(data, "false_outliers")
    grouped_fro = group_metric(data, "fro")

    fig = plt.figure(figsize=(18, 9))
    gs = fig.add_gridspec(2, 3, height_ratios=[1.5, 1.0], hspace=0.32, wspace=0.3)

    ax_keff = fig.add_subplot(gs[0, 0])
    ax_false = fig.add_subplot(gs[0, 1])
    ax_fro = fig.add_subplot(gs[0, 2])
    ax_hist = fig.add_subplot(gs[1, :])

    plot_grouped_boxplot(ax_keff, grouped_keff, r"$K_{\mathrm{eff}}$", "8A) Effective rank")
    plot_grouped_boxplot(ax_false, grouped_false, "False outliers per run", "8B) False outlier rate")
    plot_grouped_boxplot(ax_fro, grouped_fro, "Relative Frobenius error", "8C) Frobenius error vs truth")
    plot_bulk_hist(ax_hist, data)

    #fig.suptitle("Panel 8 – Heavy-tail stress test (SCM vs Tyler)", fontsize=15, fontweight="bold")
    output_path = args.output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    fig.savefig(output_path.with_suffix(".png"), dpi=300, bbox_inches="tight")
    print(f"[Panel8] Figure saved to {output_path} (+ PNG)")


if __name__ == "__main__":
    main()
